# Generated by Django 4.2.5 on 2024-04-21 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_inventory_order_orderdetail_product_user_delete_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='FIO')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('auto', models.CharField(max_length=255, verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'xaydovchi',
                'verbose_name_plural': 'xaydovchilar',
            },
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='soni')),
            ],
            options={
                'verbose_name': 'kirim(maxssulot)',
                'verbose_name_plural': 'kirim(maxssulot)',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='soni')),
            ],
            options={
                'verbose_name': 'chiqim(maxssulot)',
                'verbose_name_plural': 'chiqim(maxssulot)',
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'kirim', 'verbose_name_plural': 'kirim'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'chiqim', 'verbose_name_plural': 'chiqim'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'maxsulot', 'verbose_name_plural': 'maxsulotlar'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacture_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='qoldiq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/', verbose_name='rasm'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=12, verbose_name='narxi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yakunlandi', 'Yakunlandi')], default='Jarayonda', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nomi'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='backend.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductFromOrder', to='backend.product'),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventory', to='backend.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='backend.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='backend.driver'),
            preserve_default=False,
        ),
    ]
