# Generated by Django 4.2.5 on 2024-04-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_driver_inventoryproduct_orderproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
