# Generated by Django 5.1.4 on 2025-01-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_author_options_alter_borrowingrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForPhysicalBoosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryForElectronicBooks',
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoryforphysicalboosk', verbose_name='Категория'),
        ),
    ]
