# Generated by Django 5.1.4 on 2025-01-22 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_categoryforphysicalboosk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryforelectronicbooks',
            options={'verbose_name': 'Категория(Электронные)', 'verbose_name_plural': 'Категории(Электронные)'},
        ),
        migrations.AlterModelOptions(
            name='categoryforphysicalboosk',
            options={'verbose_name': 'Категория(Физические)', 'verbose_name_plural': 'Категории(Физические)'},
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата скачивания')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес пользователя')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные устройства')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='backend.electronicbook', verbose_name='Электронная книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог скачивания',
                'verbose_name_plural': 'Логи скачиваний',
                'ordering': ['-download_date'],
            },
        ),
    ]
