# Generated by Django 5.1.4 on 2025-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_categoryforelectronicbooks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicbook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ebook_thumbnails/', verbose_name='Обложка книги'),
        ),
    ]
