# Generated by Django 5.0.3 on 2024-04-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'chiqim(maxsulot)', 'verbose_name_plural': 'chiqim(maxsulot)'},
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.IntegerField(default=0, verbose_name='Summa')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderForRefund', to='backend.order')),
            ],
            options={
                'verbose_name': 'Vozvrat',
                'verbose_name_plural': 'Vozvratlar',
            },
        ),
        migrations.CreateModel(
            name='RefundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('count', models.IntegerField(verbose_name='soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductForRefund', to='backend.product')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refund', to='backend.refund')),
            ],
            options={
                'verbose_name': 'Vozvrat(maxsulot)',
                'verbose_name_plural': 'Vozvratlar(maxsulot)',
            },
        ),
    ]
