# Generated by Django 5.0.3 on 2024-06-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_order_status_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundproduct',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='refundproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clientlar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='RefundProduct',
        ),
    ]
