# Generated by Django 5.0.3 on 2024-07-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_group_kindergarten_question_test_testtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backend.test'),
            preserve_default=False,
        ),
    ]
