# Generated by Django 5.0.3 on 2024-07-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_answer_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='child',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testtype'),
        ),
        migrations.AddField(
            model_name='test',
            name='age_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.agerange'),
            preserve_default=False,
        ),
    ]
